# Generated by Django 5.2.10 on 2026-01-11 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_id",
                    models.CharField(max_length=20, unique=True, verbose_name="店铺id"),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=100, verbose_name="店铺名称"),
                ),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
                ("avg_price", models.FloatField(verbose_name="人均消费")),
                ("shop_score", models.FloatField(verbose_name="评分")),
                ("comment_count", models.IntegerField(verbose_name="评论数量")),
                (
                    "distance_desc",
                    models.CharField(max_length=50, null=True, verbose_name="距离描述"),
                ),
                (
                    "michelin",
                    models.CharField(max_length=10, verbose_name="米其林推荐"),
                ),
                (
                    "business_circle",
                    models.CharField(max_length=50, null=True, verbose_name="归属商圈"),
                ),
                ("food_type", models.CharField(max_length=50, verbose_name="菜系类型")),
                ("city", models.CharField(max_length=20, verbose_name="城市")),
                ("county", models.CharField(max_length=20, verbose_name="区县")),
                (
                    "business_hours",
                    models.CharField(max_length=50, null=True, verbose_name="营业时间"),
                ),
                ("location", models.CharField(max_length=30, verbose_name="地址")),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="店铺电话"),
                ),
            ],
            options={
                "verbose_name": "商铺信息",
                "verbose_name_plural": "商铺信息",
                "db_table": "food_shop_info",
            },
        ),
        migrations.CreateModel(
            name="FoodComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=100, verbose_name="店铺名称"),
                ),
                ("user_id", models.CharField(max_length=30, verbose_name="user_id")),
                ("content", models.TextField(verbose_name="content")),
                ("total_score", models.FloatField(verbose_name="综合评分")),
                (
                    "env_score",
                    models.FloatField(blank=True, null=True, verbose_name="评分_环境"),
                ),
                (
                    "taste_score",
                    models.FloatField(blank=True, null=True, verbose_name="评分_口味"),
                ),
                (
                    "service_score",
                    models.FloatField(blank=True, null=True, verbose_name="评分_服务"),
                ),
                (
                    "pag_time",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="pag_time"
                    ),
                ),
                ("publish_year", models.IntegerField(verbose_name="发布年份")),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[("正面", "正面"), ("负面", "负面"), ("中性", "中性")],
                        max_length=10,
                        null=True,
                        verbose_name="情感分类",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="情感评分(0-1)"
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        db_column="店铺id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_system.foodshop",
                        verbose_name="关联店铺",
                    ),
                ),
            ],
            options={
                "verbose_name": "商铺评论信息",
                "verbose_name_plural": "商铺评论信息",
                "db_table": "food_comment_info",
            },
        ),
    ]
