# Generated by Django 5.2.10 on 2026-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodshop",
            name="phone",
            field=models.CharField(max_length=70, null=True, verbose_name="店铺电话"),
        ),
    ]
