# Generated by Django 5.2.10 on 2026-01-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0002_alter_foodshop_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodshop",
            name="location",
            field=models.CharField(max_length=100, verbose_name="地址"),
        ),
    ]
