# Generated by Django 5.2.10 on 2026-01-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0003_alter_foodshop_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodcomment",
            name="shop",
        ),
        migrations.AddField(
            model_name="foodcomment",
            name="shop_id",
            field=models.ForeignKey(
                db_column="店铺id",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_system.foodshop",
                to_field="shop_id",
                verbose_name="关联店铺",
            ),
            preserve_default=False,
        ),
    ]
