# Generated by Django 5.2.10 on 2026-01-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0004_remove_foodcomment_shop_foodcomment_shop_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodcomment",
            name="total_score",
            field=models.DecimalField(
                decimal_places=1, max_digits=4, verbose_name="综合评分"
            ),
        ),
        migrations.AlterField(
            model_name="foodshop",
            name="shop_score",
            field=models.DecimalField(
                decimal_places=1, max_digits=4, verbose_name="综合评分"
            ),
        ),
    ]
