# Generated by Django 5.2.10 on 2026-01-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0006_shopcollect"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentAnalysisTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="任务ID"
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=200, verbose_name="任务名称"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("full", "全部分析"),
                            ("incremental", "增量分析"),
                            ("reanalyze", "重新分析"),
                            ("test", "测试分析"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "total_comments",
                    models.IntegerField(default=0, verbose_name="总评论数"),
                ),
                (
                    "processed_comments",
                    models.IntegerField(default=0, verbose_name="已处理数"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="成功数"),
                ),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("progress", models.FloatField(default=0, verbose_name="进度(%)")),
                (
                    "use_enhanced_algorithm",
                    models.BooleanField(default=True, verbose_name="使用增强算法"),
                ),
                (
                    "batch_size",
                    models.IntegerField(default=500, verbose_name="批处理大小"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "result_summary",
                    models.JSONField(blank=True, null=True, verbose_name="结果摘要"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="处理时间(秒)"
                    ),
                ),
                (
                    "comments_per_second",
                    models.FloatField(
                        blank=True, null=True, verbose_name="处理速度(条/秒)"
                    ),
                ),
            ],
            options={
                "verbose_name": "情感分析任务",
                "verbose_name_plural": "情感分析任务",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_id"], name="user_system_task_id_f6f091_idx"
                    ),
                    models.Index(
                        fields=["status"], name="user_system_status_f0dd04_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="user_system_created_597685_idx"
                    ),
                ],
            },
        ),
    ]
