# Generated by Django 5.2.10 on 2026-03-15 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0007_sentimentanalysistask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "用户"), ("assistant", "AI助手")],
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI对话历史",
                "verbose_name_plural": "AI对话历史",
                "db_table": "ai_chat_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flavor_pref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如：辣、甜、咸、麻、清淡（多个用逗号分隔）",
                        max_length=200,
                        verbose_name="口味偏好",
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="如：不吃香菜、清真、素食、海鲜过敏",
                        verbose_name="饮食禁忌",
                    ),
                ),
                (
                    "avg_budget",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lt50", "50元以内"),
                            ("50_150", "50~150元"),
                            ("150_500", "150~500元"),
                            ("gt500", "500元以上"),
                        ],
                        default="50_150",
                        max_length=20,
                        verbose_name="常用消费区间",
                    ),
                ),
                (
                    "frequent_areas",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如：海淀、朝阳、西城（多个用逗号分隔）",
                        max_length=200,
                        verbose_name="常驻区域",
                    ),
                ),
                (
                    "scene_weight",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("taste_first", "口味优先（老饕派）"),
                            ("env_first", "环境优先（商务派）"),
                            ("price_first", "性价比优先"),
                            ("balanced", "均衡考虑"),
                        ],
                        default="balanced",
                        max_length=20,
                        verbose_name="推荐偏好场景",
                    ),
                ),
                (
                    "has_car",
                    models.BooleanField(default=False, verbose_name="需要停车位"),
                ),
                (
                    "has_child",
                    models.BooleanField(
                        default=False, verbose_name="携带儿童（需儿童座椅）"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户偏好设置",
                "verbose_name_plural": "用户偏好设置",
                "db_table": "user_profile",
            },
        ),
    ]
