# Generated by Django 5.2.10 on 2026-03-21 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0008_aichathistory_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=100, verbose_name="商家名称/公司"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=30, verbose_name="联系电话"),
                ),
                (
                    "id_card_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="营业执照/身份证号"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="已通过商家认证"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="商家账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "商家资料",
                "verbose_name_plural": "商家资料",
                "db_table": "merchant_profile",
            },
        ),
        migrations.CreateModel(
            name="ShopApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=100, verbose_name="店铺名称"),
                ),
                ("food_type", models.CharField(max_length=50, verbose_name="菜系类型")),
                ("county", models.CharField(max_length=20, verbose_name="区县")),
                (
                    "business_circle",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="所属商圈"
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="详细地址")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="店铺电话"
                    ),
                ),
                (
                    "business_hours",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="营业时间"
                    ),
                ),
                (
                    "avg_price",
                    models.FloatField(default=0, verbose_name="人均消费(元)"),
                ),
                ("longitude", models.FloatField(default=116.404, verbose_name="经度")),
                ("latitude", models.FloatField(default=39.915, verbose_name="纬度")),
                ("description", models.TextField(blank=True, verbose_name="店铺简介")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, verbose_name="驳回理由"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_shop",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="user_system.foodshop",
                        verbose_name="关联店铺",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请商家",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商家店铺申请",
                "verbose_name_plural": "商家店铺申请",
                "db_table": "shop_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShopClickLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_logs",
                        to="user_system.foodshop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "店铺点击记录",
                "verbose_name_plural": "店铺点击记录",
                "db_table": "shop_click_log",
                "indexes": [
                    models.Index(
                        fields=["shop", "clicked_at"],
                        name="shop_click__shop_id_868620_idx",
                    )
                ],
            },
        ),
    ]
