# Generated by Django 5.2.10 on 2026-03-21 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0009_merchantprofile_shopapplication_shopclicklog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="business_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="商家地址"),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="business_license_no",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="营业执照号"
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="business_scope",
            field=models.CharField(blank=True, max_length=255, verbose_name="经营范围"),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="id_card_front_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="merchant/id_card/",
                verbose_name="身份证正面图片",
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="legal_person_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="法人姓名"),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="license_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="merchant/license/",
                verbose_name="营业执照图片",
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="qualification_status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "审核通过"),
                    ("rejected", "审核驳回"),
                ],
                default="pending",
                max_length=20,
                verbose_name="资质审核状态",
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="review_note",
            field=models.TextField(blank=True, verbose_name="审核备注/驳回原因"),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="资质审核时间"
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_merchants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="资质审核人",
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="shop_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="店铺地址"),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="shop_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="merchant/shop/",
                verbose_name="店铺门头/环境图",
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="shop_name",
            field=models.CharField(blank=True, max_length=120, verbose_name="店铺名称"),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="merchantprofile",
            name="id_card_no",
            field=models.CharField(blank=True, max_length=50, verbose_name="身份证号"),
        ),
    ]
